apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullnameOverride | default .Release.Name }}
  labels:
    app: {{ .Values.fullnameOverride | default "library-system" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.fullnameOverride | default "library-system" }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullnameOverride | default "library-system" }}
    spec:
      containers:
        - name: library-system
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8080

          # =========================
          # ENV VARIABLES
          # =========================
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}

            - name: DB_URL
              value: {{ .Values.db.url | quote }}

            - name: DB_USERNAME
              value: {{ .Values.db.username | quote }}

            - name: DB_PASSWORD
              value: {{ .Values.db.password | quote }}

          # =========================
          # RESOURCE LIMITS
          # =========================
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          # =========================
          # HEALTH CHECKS
          # =========================
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10