apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-system
  namespace: library-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-system

  template:
    metadata:
      labels:
        app: library-system

    spec:
      containers:
        - name: library-system
          image: binaydev/library-system:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: url

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20