replicaCount: 2

# =========================
# IMAGE CONFIGURATION
# =========================
image:
  repository: binaydev/library-system
  pullPolicy: Always
  tag: "v1"

# =========================
# NAME OVERRIDES
# =========================
nameOverride: ""
fullnameOverride: library-system

# =========================
# SERVICE ACCOUNT
# =========================
serviceAccount:
  create: false
  automount: true

# =========================
# SERVICE CONFIG
# =========================
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# =========================
# INGRESS (disabled for now)
# =========================
ingress:
  enabled: false

# =========================
# HTTPROUTE (FIX FOR YOUR ERROR)
# =========================
httpRoute:
  enabled: false
  parentRefs: []
  hostnames: []
  rules: []

# =========================
# SPRING BOOT ENVIRONMENT
# =========================
env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
  SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS: "false"

# =========================
# DATABASE CONFIG
# =========================
db:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/library_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root123
  
  SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: "0"
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "30000"
  SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT: "5000"

# =========================
# RESOURCE LIMITS
# =========================
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi


# =========================
# AUTOSCALING (DISABLED FOR NOW)
# =========================
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

# =========================
# NODE PLACEMENT
# =========================
nodeSelector: {}
tolerations: []
affinity: {}