name: Library System CI/CD Pipeline

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: library-system
  DOCKER_IMAGE: ${{ secrets.DOCKER_USER }}/library-system

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:

      # =========================
      # 1. Checkout Code
      # =========================
      - name: Checkout Repository
        uses: actions/checkout@v4

      # =========================
      # 2. Setup Java 17
      # =========================
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # =========================
      # 3. Build Spring Boot App
      # =========================
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # =========================
      # 4. Login to DockerHub
      # =========================
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      # =========================
      # 5. Build Docker Image
      # =========================
      - name: Build Docker Image
        run: docker build -t $DOCKER_IMAGE:latest .

      # =========================
      # 6. Push Docker Image
      # =========================
      - name: Push Docker Image
        run: docker push $DOCKER_IMAGE:latest


  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

      # =========================
      # 7. Checkout Code (for Helm)
      # =========================
      - name: Checkout Repository
        uses: actions/checkout@v4

      # =========================
      # 8. Setup Kubernetes config
      # =========================
      - name: Setup Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

      # =========================
      # 9. Install Helm
      # =========================
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # =========================
      # 10. Deploy using Helm
      # =========================
      - name: Deploy to Kubernetes using Helm
        run: |
          export KUBECONFIG=kubeconfig
          helm upgrade --install library-system ./helm/library-system